'use client';
import {FormEvent,useState} from 'react';
import {ArrowUpRight,Bot,Check,MapPin,Search,ShieldCheck,Sparkles} from 'lucide-react';

type Candidate={id:string;name:string;address:string;rating:number|null;reviews:number;website:string|null;score:number;priority:string};

export default function AdminClient(){
 const[niche,setNiche]=useState('');const[location,setLocation]=useState('');const[rows,setRows]=useState<Candidate[]>([]);const[selected,setSelected]=useState<string[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 async function search(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');setSelected([]);try{const r=await fetch('/api/agents/prospect/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({niche,location})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha na busca');setRows(j.candidates||[])}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
 async function approve(){if(!selected.length)return;setBusy(true);setMsg('');try{const prospects=rows.filter(x=>selected.includes(x.id)).map(x=>({id:x.id,name:x.name,address:x.address,rating:x.rating,reviews:x.reviews,score:x.score,niche,region:location}));const r=await fetch('/api/agents/prospect/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approvedIds:selected,prospects})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha na aprovação');setMsg(`${selected.length} prospect${selected.length>1?'s':''} aprovado${selected.length>1?'s':''}. Diagnósticos prontos para a régua de contato.`);setSelected([])}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <main className="adminShell"><aside><a className="adminBrand" href="/admin"><span><MapPin size={18}/></span>MeuLocal <b>Admin</b></a><nav><a className="active"><Search/>Prospecção</a><a><Sparkles/>Aprendizado</a><a><Bot/>Agentes</a></nav><div className="adminSafety"><ShieldCheck/><div><strong>Human-in-the-loop</strong><small>Nenhum primeiro contato é enviado sem sua aprovação.</small></div></div></aside><section className="adminMain"><header><div><span>CENTRO DE COMANDO</span><h1>Prospecção</h1><p>Diga ao agente qual mercado explorar. Você decide quem será abordado.</p></div><div className="agentOnline"><i/> Agente disponível</div></header><form className="commandCard" onSubmit={search}><div className="commandIcon"><Bot/></div><div className="commandFields"><label>O que você quer prospectar?<input value={niche} onChange={e=>setNiche(e.target.value)} placeholder="Ex.: empresas que alugam geradores" required/></label><label>Onde?<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Ex.: São Paulo, SP" required/></label></div><button disabled={busy}>{busy?'Pesquisando...':'Buscar oportunidades'} <ArrowUpRight/></button></form>{msg&&<div className="adminMessage">{msg}</div>}{rows.length>0&&<><div className="resultHeader"><div><span>OPORTUNIDADES ENCONTRADAS</span><h2>Prioridade sugerida pelo MeuLocal</h2><p>Ordenadas do menor Score para o maior. Revise antes de autorizar qualquer contato.</p></div><button className="approveBtn" onClick={approve} disabled={!selected.length||busy}><Check/> Aprovar {selected.length||''} {selected.length===1?'prospect':'prospects'}</button></div><div className="prospectList">{rows.map((r,i)=><article key={r.id} className={selected.includes(r.id)?'selected':''} onClick={()=>toggle(r.id)}><div className="selectBox">{selected.includes(r.id)&&<Check/>}</div><div className="rank">#{i+1}</div><div className="prospectInfo"><strong>{r.name}</strong><span>{r.address}</span><small>{r.rating?`★ ${r.rating}`:'Sem nota'} · {r.reviews} avaliações</small></div><div className="scoreBox"><span>Score MeuLocal</span><strong>{r.score}<small>/100</small></strong><em>{r.priority.replace('_',' ')}</em></div></article>)}</div></>}</section></main>
}
