export const meulocalBusinessRules = {
  commercial: {
    officialMonthlyPriceBRL: 397,
    founderMonthlyPriceBRL: 297,
    founderPriceIsException: true,
    publicOfferName: 'MeuLocal',
    promise: 'Mais avaliações. Mais presença no Google. Mais clientes locais.',
    products: {
      reputation: {
        name: 'MeuLocal',
        status: 'active',
        monthlyPriceBRL: 397,
        objective: 'Reputação no Google, crescimento de avaliações e inteligência local.',
      },
      seo: {
        name: 'MeuLocal SEO',
        status: 'validation',
        priceStatus: 'to_be_defined',
        objective: 'Descobrir palavras-chave, oportunidades de conteúdo, rankings, concorrentes, backlinks e prioridades técnicas de SEO.',
        mayBeSoldStandalone: true,
        mayBeSoldAsAddon: true,
        doNotBundleByDefaultWithReputationPlan: true,
      },
    },
  },
  systems: {
    intelligenceSystem: 'supabase',
    executionSystem: 'highlevel',
    customerFacingSystem: 'meulocal',
    seoIntelligenceSystem: 'openseo',
    neverExposeHighLevelToCustomer: true,
    openseoIsInternalInfrastructure: true,
  },
  seo: {
    provider: 'openseo',
    integrationMode: 'mcp_or_api_adapter',
    capabilities: [
      'keyword_research',
      'keyword_clustering',
      'rank_tracking',
      'competitor_insights',
      'backlinks',
      'site_audits',
      'local_seo',
      'ai_visibility',
    ] as const,
    recommendationsMustBeEvidenceBased: true,
    neverInventSearchVolume: true,
    neverInventKeywordDifficulty: true,
    neverInventRankPosition: true,
    neverInventBacklinkCounts: true,
    separateObservedDataFromRecommendations: true,
    requireHumanApprovalBeforePublishingContent: true,
    avoidProgrammaticThinContent: true,
    preferHighIntentLocalKeywords: true,
  },
  whatsapp: {
    transportOwnedByHighLevel: true,
    neverConnectMeuLocalDirectlyToWhatsAppProvider: true,
    inboundEventsMustReturnToMeuLocal: true,
    futureHighLevelWebhookRequired: true,
    webhookPurpose: [
      'message_status',
      'inbound_reply',
      'opt_out',
      'conversion_attribution',
      'learning_event',
    ] as const,
  },
  prospecting: {
    requiresHumanApprovalBeforeFirstContact: true,
    maxOutboundMessagesPerProspect: 3,
    diagnosticMustBeEvidenceBased: true,
    stopOnOptOut: true,
    stopOnConversion: true,
    stopAfterThirdMessageWithoutConversion: true,
    noMacroStrategyChangeWithoutApproval: true,
    whatsappHomeLinkAfterPositiveIntent: true,
    competitionScope: {
      defaultMode: 'auto',
      radiusMetersIsOnlyAHeuristic: true,
      supportedModes: ['local_radius','city_region','search_market'] as const,
      hyperlocalExamples: ['barbearia','restaurante','academia','pet shop'] as const,
      searchMarketExamples: ['aluguel de geradores','software','serviços B2B','equipamentos','fornecedores'] as const,
      rule: 'Concorrente é quem disputa a mesma intenção de busca e o mesmo cliente, mesmo que esteja fora do raio físico.',
    },
    outreachCopyMustMatchEvidenceScope: true,
    neverSayNearbyWhenComparisonIsSearchMarket: true,
    neverClaimRadiusIfRadiusWasNotActuallyUsed: true,
  },
  onboarding: {
    requiresConfirmedPaymentBeforeActivation: true,
    dedicatedHighLevelLocationPerCustomer: true,
    provisionHighLevelBeforeChannelSetup: true,
    allowManualProvisioningFallback: true,
    googleBusinessConsentRequired: true,
    customerImportOptional: true,
    customerImportRequiresValidation: true,
    customerImportRequiresDedupe: true,
    customerImportRequiresFinalConfirmation: true,
    neverSendEndCustomerMessagesBeforeFinalConfirmation: true,
  },
  advisor: {
    observedFactsMustBeSeparatedFromRecommendations: true,
    neverInventMetrics: true,
    neverExposeIdentifiableCrossCustomerData: true,
    preferAggregateLearning: true,
  },
  data: {
    minimizePersonalData: true,
    doNotPersistRawGoogleReviewTextByDefault: true,
    storeStructuredLearningEvents: true,
    everyExternalEventShouldBeIdempotent: true,
  },
} as const;

export type MeuLocalBusinessRules = typeof meulocalBusinessRules;
