export const agentModels = {
  prospectDiscovery: 'gpt-5.6-luna',
  prospectDecision: 'gpt-5.6-terra',
  onboarding: 'gpt-5.6-terra',
  customerAdvisor: 'gpt-5.6-sol',
  seoIntelligence: 'gpt-5.6-terra',
} as const;

export const agentPolicies = {
  prospecting: {
    requiresHumanApprovalBeforeContact: true,
    maxCandidatesPerSearch: 30,
    maxApprovedBatch: 10,
    defaultRadiusMeters: 3000,
    minimumGoogleRating: 4.0,
    prioritizeScoreBelow: 55,
    channels: ['email', 'whatsapp'] as const,
    maxOutboundMessages: 3,
    firstMessageIncludesDiagnostic: true,
    diagnosticCtaLabel: 'Quer saber como melhorar suas avaliações?',
    diagnosticCtaDestination: '/',
    stopAfterConversion: true,
    stopAfterOptOut: true,
    stopAfterThirdMessageWithoutConversion: true,
    humanApprovalAppliesBeforeFirstContactOnly: true,
  },
  onboarding: {
    neverExposeHighLevel: true,
    neverSendCustomerMessagesBeforeFinalConfirmation: true,
    allowImportSkip: true,
    provisionDedicatedGhlLocationPerCustomer: true,
    provisionBeforeChannelSetup: true,
    neverReuseCustomerLocationAcrossBusinesses: true,
    neverDeleteOrOverwriteExistingLocationWithoutApproval: true,
    manualProvisioningFallbackWhenApiUnavailable: true,
    neverBlockCustomerExperienceOnManualProvisioning: true,
  },
  seo: {
    provider: 'openseo',
    externalMetricsRequireEvidence: true,
    publishRequiresHumanApproval: true,
    allowStandaloneProduct: true,
    allowAddonProduct: true,
    avoidThinProgrammaticPages: true,
    prioritizeCommercialAndLocalIntent: true,
  },
} as const;
