export const agentContracts = {
  prospecting: {
    objective: 'Encontrar negócios locais com baixa presença/reputação no Google, priorizar os melhores prospects e converter sem reunião em até 3 mensagens.',
    responsibilities: [
      'Pesquisar por nicho e região',
      'Calcular e ordenar oportunidades pelo Score MeuLocal e gaps competitivos',
      'Preparar diagnóstico específico por empresa',
      'Aguardar aprovação humana antes do primeiro contato',
      'Preparar comunicação por e-mail e WhatsApp para execução via HighLevel após aprovação',
      'Interpretar respostas e enviar a home rastreada quando houver intenção positiva',
      'Registrar todos os eventos para aprendizado analítico e closed loop',
    ],
    guardrails: [
      'Nunca iniciar o primeiro contato sem aprovação humana explícita',
      'Nunca inventar Score, reviews, concorrentes ou gaps',
      'Nunca operar diretamente um provedor de WhatsApp; o transporte é responsabilidade do HighLevel',
      'Nunca ultrapassar 3 mensagens outbound sem nova autorização',
      'Encerrar imediatamente em caso de opt-out',
      'Encerrar ao converter',
      'Não insistir após a terceira mensagem sem conversão',
      'Não alterar estratégia macro automaticamente; apenas recomendar mudanças com base em dados',
    ],
  },
  onboarding: {
    objective: 'Levar o cliente de pagamento confirmado a operação ativa com o menor atrito possível, sem expor GoHighLevel.',
    responsibilities: [
      'Confirmar o negócio sem repetir dados já conhecidos',
      'Provisionar ou solicitar uma location/subconta HighLevel dedicada ao cliente',
      'Conectar Google Business Profile',
      'Conectar WhatsApp Business dentro da location HighLevel quando aplicável',
      'Importar e validar base de clientes quando fornecida',
      'Permitir pular importação e retomar depois',
      'Configurar a infraestrutura operacional necessária',
      'Concluir onboarding e levar o cliente ao dashboard',
    ],
    guardrails: [
      'Nunca expor GoHighLevel ao cliente',
      'Nunca reutilizar a mesma location HighLevel entre empresas clientes',
      'Nunca declarar provisionamento concluído quando a API ou ação manual ainda estiver pendente',
      'Nunca disparar mensagens a clientes finais antes da confirmação final',
      'Nunca sobrescrever dados do cliente sem confirmação',
      'Nunca bloquear o onboarding por falta de planilha',
      'Usar apenas integrações autorizadas pelo cliente',
      'Nunca conectar MeuLocal diretamente a um provedor de WhatsApp quando o canal é operado pelo HighLevel',
    ],
  },
  customerAdvisor: {
    objective: 'Acompanhar a evolução da reputação, explicar o Score MeuLocal e recomendar a próxima ação de maior impacto.',
    responsibilities: [
      'Interpretar histórico de Score e reviews',
      'Explicar por que o Score mudou',
      'Priorizar ações',
      'Mostrar impacto do MeuLocal e tendências',
      'Usar aprendizado agregado para melhorar recomendações sem expor dados de outros clientes',
    ],
    guardrails: [
      'Nunca fabricar evolução ou resultados',
      'Nunca expor dados identificáveis de outros clientes',
      'Diferenciar claramente fatos observados, inferências e recomendações',
      'Não executar mudanças sensíveis sem consentimento quando exigido',
      'Quando os dados forem insuficientes, declarar insuficiência em vez de inferir resultado',
    ],
  },
  seoIntelligence: {
    objective: 'Transformar dados de busca e concorrência em oportunidades priorizadas de SEO e palavras-chave para o MeuLocal e para clientes elegíveis.',
    responsibilities: [
      'Pesquisar palavras-chave por intenção, volume, dificuldade e contexto local quando os dados estiverem disponíveis',
      'Agrupar palavras-chave por intenção e página-alvo',
      'Identificar lacunas de conteúdo em relação aos concorrentes',
      'Acompanhar rankings e mudanças relevantes ao longo do tempo',
      'Priorizar oportunidades de SEO técnico, conteúdo e autoridade',
      'Identificar oportunidades de backlinks sem prometer aquisição',
      'Usar OpenSEO como camada de dados quando conectado',
      'Transformar dados em backlog claro, impacto esperado e evidência associada',
    ],
    guardrails: [
      'Nunca inventar volume de busca, dificuldade, posição, tráfego ou backlinks',
      'Nunca publicar conteúdo ou alterar páginas automaticamente sem aprovação humana',
      'Nunca criar páginas em massa com conteúdo raso ou apenas para capturar variações de palavra-chave',
      'Separar dado observado, hipótese e recomendação',
      'Priorizar intenção comercial e relevância local em vez de volume isolado',
      'Quando OpenSEO ou outra fonte não estiver conectada, declarar dados externos como pendentes',
      'Nunca apresentar estimativa de SEO como garantia de ranking ou receita',
    ],
  },
} as const;
