'use client';
import '../dashboard/dashboard.css';
import {FormEvent,useState} from 'react';
import {ArrowRight,LockKeyhole,MapPin} from 'lucide-react';
import {createClient} from '@supabase/supabase-js';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export default function LoginPage(){
 const[mode,setMode]=useState<'login'|'create'>('login'); const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[confirm,setConfirm]=useState(''); const[error,setError]=useState(''); const[loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');if(!url||!key){setError('A área do cliente ainda está sendo ativada. Tente novamente em instantes.');return}if(mode==='create'&&password!==confirm){setError('As senhas precisam ser iguais.');return}setLoading(true);const supabase=createClient(url,key);const result=mode==='create'?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setLoading(false);if(result.error){setError(mode==='login'?'E-mail ou senha inválidos.':'Não foi possível criar seu acesso. Verifique os dados e tente novamente.');return}window.location.href=mode==='create'?'/onboarding':'/dashboard';}
 return <main className="loginPage"><header className="nav container"><a className="brand" href="/"><span className="brandMark"><MapPin size={19}/></span>MeuLocal</a></header><section className="loginWrap container"><div className="loginCard"><div className="loginIcon"><LockKeyhole size={23}/></div><span className="stepLabel">ÁREA DO CLIENTE</span><h1>{mode==='login'?'Acesse seu MeuLocal':'Crie seu acesso'}</h1><p>{mode==='login'?'Veja seu Score, avaliações e evolução em poucos segundos.':'Crie sua senha para acompanhar os resultados do seu negócio.'}</p><form onSubmit={submit}><label>E-mail<input type="email" inputMode="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com.br" required/></label><label>Senha<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" minLength={8} required/></label>{mode==='create'&&<label>Confirmar senha<input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="••••••••" minLength={8} required/></label>}{error&&<div className="loginError" role="alert">{error}</div>}<button className="primary loginSubmit" type="submit" disabled={loading}>{loading?'Aguarde...':mode==='create'?'Criar meu acesso':'Entrar'} {!loading&&<ArrowRight size={18}/>}</button></form><button className="linkButton loginSwitch" type="button" onClick={()=>{setError('');setMode(mode==='login'?'create':'login')}}>{mode==='login'?'Primeiro acesso? Criar senha':'Já tenho acesso'}</button></div><small>Seu acesso é exclusivo ao ambiente MeuLocal.</small></section></main>}
