'use client';
import {useEffect,useState} from 'react';
import {BarChart3,Bot,MapPin,Search,Sparkles,TrendingUp} from 'lucide-react';

type Row={label:string;contacts:number;positiveReplies:number;conversions:number;conversionRate:number};
type Payload={niches:Row[];channels:Row[];messages:Row[];totals:{contacts:number;positiveReplies:number;conversions:number;conversionRate:number}};

export default function LearningClient(){const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{fetch('/api/admin/learning').then(r=>r.json()).then(j=>setData(j)).finally(()=>setLoading(false))},[]);return <main className="adminShell"><aside><a className="adminBrand" href="/admin"><span><MapPin size={18}/></span>MeuLocal <b>Admin</b></a><nav><a href="/admin"><Search/>Prospecção</a><a className="active" href="/admin/aprendizado"><Sparkles/>Aprendizado</a><a href="/admin/agentes"><Bot/>Agentes</a></nav></aside><section className="adminMain"><header><div><span>LOOP DE APRENDIZADO</span><h1>Aprendizado</h1><p>O que a prospecção está ensinando ao MeuLocal.</p></div></header>{loading?<p>Carregando dados...</p>:!data?<p>Ainda não há dados suficientes.</p>:<><div className="learningKpis"><article><span>Contatos</span><strong>{data.totals.contacts}</strong></article><article><span>Respostas positivas</span><strong>{data.totals.positiveReplies}</strong></article><article><span>Conversões</span><strong>{data.totals.conversions}</strong></article><article><span>Taxa de conversão</span><strong>{data.totals.conversionRate.toFixed(1)}%</strong></article></div><LearningTable title="Conversão por nicho" icon={<TrendingUp/>} rows={data.niches}/><LearningTable title="Conversão por canal" icon={<BarChart3/>} rows={data.channels}/><LearningTable title="Conversão por mensagem" icon={<Sparkles/>} rows={data.messages}/></>}</section></main>}

function LearningTable({title,icon,rows}:{title:string;icon:React.ReactNode;rows:Row[]}){return <section className="learningPanel"><div className="learningTitle">{icon}<h2>{title}</h2></div>{rows.length===0?<p className="panelCopy">Ainda sem volume suficiente.</p>:<div className="learningRows">{rows.map((r,i)=><div key={`${r.label}-${i}`}><strong>{r.label}</strong><span>{r.contacts} contatos</span><span>{r.positiveReplies} respostas +</span><span>{r.conversions} conversões</span><b>{r.conversionRate.toFixed(1)}%</b></div>)}</div>}</section>}
